pipeline {
	agent {
		kubernetes {
			defaultContainer 'buildpack'
			yaml '''
kind: Pod
spec:
  containers:
  - name: buildpack
    image: maxmorhardt/topfilms-jenkins-buildpack:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
'''
		}
	}

	parameters {
		string(name: 'BRANCH', defaultValue: params.BRANCH ?: 'main', description: 'Branch to checkout in k8s repo', trim: true)
	}

	environment { 
		APP_NAME = 'rancher'
		GITHUB_URL = 'https://github.com/Top-Films/k8s'
	}

	stages {

		stage('Git Clone') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "${params.BRANCH}"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "${env.GITHUB_URL}"
						]]
					)

					sh 'ls -lah'
				}
			}
		}

		stage('Deploy Rancher') {
			steps {
				script {
					withCredentials([
						file(credentialsId: 'ca-cert', variable: 'CA_CERT'),
						file(credentialsId: 'ca-cert-private-key', variable: 'CA_CERT_PRIVATE_KEY'),
						file(credentialsId: 'kube-config', variable: 'KUBE_CONFIG')
					]) {
						sh 'mkdir -p $WORKSPACE/.kube && cp $KUBE_CONFIG $WORKSPACE/.kube/config'

						sh '''
							cp $CA_CERT ./cert.pem
							cp $CA_CERT_PRIVATE_KEY ./key.pem

							kubectl delete secret rancher.topfilms.io-tls -n cattle-system || true
							kubectl create secret tls rancher.topfilms.io-tls --cert=cert.pem --key=key.pem -n cattle-system
						'''

						sh """
							cd $APP_NAME
							
							helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
							helm repo update

							helm upgrade $APP_NAME rancher-latest/$APP_NAME -f values.yaml --install --atomic --debug --history-max=3 --namespace cattle-system
						"""
					}
				}
			}
		}

	}
}