pipeline {
	agent {
		kubernetes {
			defaultContainer 'dind'
			yaml '''
kind: Pod
spec:
  containers:
  - name: dind
    image: docker:27-dind
    imagePullPolicy: Always
    securityContext:
      privileged: true
'''
		}
	}

	parameters {
		string(name: 'BRANCH', defaultValue: params.BRANCH ?: 'main', description: 'Branch to checkout', trim: true)
		string(name: 'VERSION', defaultValue: params.VERSION ?: '1.0', description: 'Major and minor version of the application', trim: true)
	}

	environment { 
		APP_NAME = 'topfilms-jenkins-buildpack'
		APP_VERSION = "${env.VERSION}.${env.BUILD_NUMBER}"
		GITHUB_URL = 'https://github.com/Top-Films/k8s'
	}

	stages {

		stage('Git Clone') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					sh 'ls -lah'
				}
			}
		}

		stage('Docker Push Artifact') {
			steps {
				script {
					withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
						
						sh 'docker buildx build --platform linux/arm64/v8 . --tag $DOCKER_USERNAME/$APP_NAME:$APP_VERSION --tag $DOCKER_USERNAME/$APP_NAME:latest --file jenkins/buildpack/Dockerfile'
						sh 'docker push $DOCKER_USERNAME/$APP_NAME --all-tags'
					}
				}
			}
		}

	}
}