pipeline {
	agent {
		kubernetes {
			defaultContainer 'dind'
			yaml '''
kind: Pod
spec:
  containers:
  - name: dind
    image: docker:27-dind
    imagePullPolicy: Always
    securityContext:
      privileged: true
'''
		}
	}

	parameters {
		string(name: 'BRANCH', defaultValue: params.KEYWIND_BRANCH ?: 'main', description: 'Branch to checkout')
		string(name: 'VERSION', defaultValue: params.APP_VERSION ?: '1.0', description: 'Major and minor version of the application')
	}

	environment { 
		APP_NAME = 'topfilms-jenkins-buildpack'
		APP_VERSION = "${params.VERSION}.${env.BUILD_NUMBER}"
		K8S_GITHUB_URL = 'https://github.com/Top-Films/k8s'
	}

	stages {

		stage('Git Clone') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "${params.BRANCH}"
						]],
						userRemoteConfigs: [[
							credentialsId: '827446b2-c8ac-4420-bcda-87696bb62634',
							url: "${env.K8S_GITHUB_URL}"
						]]
					)

					sh 'ls -lah'
				}
			}
		}

		stage('Docker Push Artifact') {
			steps {
				script {
					withCredentials([usernamePassword(credentialsId: '9bbf8bb7-1489-4260-a7a0-afce14eea51b', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
						sh 'docker buildx build --platform linux/arm64/v8 . -t $DOCKER_USERNAME/$APP_NAME:$APP_VERSION -t $DOCKER_USERNAME/$APP_NAME:latest -f jenkins/buildpack/Dockerfile'
						sh 'docker push $DOCKER_USERNAME/$APP_NAME -a'
					}
				}
			}
		}

	}
}