apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.7
          volumeMounts:
            - mountPath: "/var/keycloak"
              name: keycloak-cert
              readOnly: true
          args: 
            - "start"
            - "--db=postgres"
            - "--db-username=$(DB_USERNAME)"
            - "--db-password=$(DB_PASSWORD)"
            - "--db-url=$(DB_HOST)"
            - "--https-certificate-file=/var/keycloak/cert.pem"
            - "--https-certificate-key-file=/var/keycloak/key.pem"
            - "--hostname=auth.topfilms.io"
          env:
            - name: KC_PROXY
              value: edge
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: admin-username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: admin-password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: db-host
          ports:
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /realms/master
              port: 8443
      volumes:
        - name: keycloak-cert
          secret:
            secretName: keycloak-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - auth.topfilms.io
      secretName: auth.topfilms.io-tls
  rules:
    - host: auth.topfilms.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8443