global:
  storageClass: "postgres-sc"
  postgresql:
    auth:
      postgresPassword: ""
      username: ""
      password: ""
      database: "topfilms"

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: ""
  nodeSelector:
    postgres-port-forwarded: 'true'

volumePermissions:
  enabled: true