image:
  pullPolicy: IfNotPresent
  repository: supertokens/supertokens-postgresql
  tag: '7.0'
  env:
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbUsername
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbPassword
    - name: POSTGRESQL_HOST
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbHost
    - name: POSTGRESQL_PORT
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbPort
    - name: POSTGRESQL_DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbName
    - name: API_KEYS
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: apiKey

service:
  type: ClusterIP
  port: 80
  targetPort: 3567

ingress:
  className: nginx
  hosts:
    - host: supertokens.topfilms.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: supertokens.topfilms.io-tls
      hosts:
        - supertokens.topfilms.io

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
