image:
  repository: supertokens/supertokens-postgresql
  tag: '9.0'
  pullPolicy: Always
  replicas: 1
  env:
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbUsername
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbPassword
    - name: POSTGRESQL_HOST
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbHost
    - name: POSTGRESQL_PORT
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbPort
    - name: POSTGRESQL_DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: dbName
    - name: API_KEYS
      valueFrom:
        secretKeyRef:
          name: supertokens-core-env
          key: apiKey
  readinessProbe:
    path: /hello
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  livenessProbe:
    path: /hello
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3567

ingress:
  className: nginx
  hosts:
    - host: supertokens.topfilms.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: supertokens.topfilms.io-tls
      hosts:
        - supertokens.topfilms.io

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
