global:
  storageClass: postgres
  postgresql:
    auth:
      username: maxmorhardt
      database: topfilms
      existingSecret: postgres-credentials
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30543
  nodeSelector:
    kubernetes.io/hostname: max-worker

volumePermissions:
  enabled: true

 persistence:
    size: 1024Gi